[build]
  command = "npm run build"
  publish = "dist"

# optional: pin Node version Netlify should use
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
